name: Lint
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '*'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run GolangCI-Lint
        uses: docker://matousdz/golangci-lint-action:v1.0.0
        with:
          config: .golangci.yml

